ARG VERSION=latest
ARG DOCKER_REPO
FROM $DOCKER_REPO/distil-pipeline-runner-env:$VERSION

# Using the requirements file results in a single cache layer for python packages and
# dependencies, which makes the image build very slowly when a new python package is added.
# As an optimization, we intentionally run package installation as a manual set of RUN
# commands, and ignore the requirements.txt file.  We could template this Dockerfile
# and have the build.sh script copy the contents of the requirements file in to reduce
# duplication.
#
# COPY requirements.txt ./requirements.txt
# RUN pip3 install -r requirements.txt --process-dependency-links

# D3M baseline packages - do this first because there are a lot of dependencies.
# Common primitives has a lot of dependencies that aren't used, so we stop transitive resolution.  Torch is
# the only that is required due to its use in a shared utilities function.
RUN pip3 install -e git+https://gitlab.com/datadrivendiscovery/common-primitives.git@bfb1c37ee2b43b785cdbcfb3acc13d19a4f9a474#egg=common_primitives --no-deps && \
    pip3 install torch==1.0.0 && \
    pip3 install -e git+https://gitlab.com/datadrivendiscovery/ta3ta2-api.git@dist-python#egg=ta3ta2_utils;

# NK Primitives
RUN pip3 install -e git+https://github.com/NewKnowledge/pcafeatures-d3m-wrapper.git@903ea261a3959bd7ee2a3fe78273437d351cf636#egg=PcafeaturesD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/simon-d3m-wrapper.git@6484e6776c3c96a60bd7ad9cad90e67c6c05a6ed#egg=SimonD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/datacleaning-d3m-wrapper.git@e35dd8a3e658f4e471828260ed1953577b03dd1f#egg=DatacleaningD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/duke-d3m-wrapper.git@1c5e5f20fced72f042581a2f9cfca41557a2d85d#egg=DukeD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/croc-d3m-wrapper.git@86695826d2481949c55e38020be222d231962806#egg=CROCd3mWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/unicorn-d3m-wrapper.git@6c324133f932068600c4b55047b0eaf194a5d39f#egg=UNICORNd3mWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/TimeSeries-D3M-Wrappers.git@7fe689115f302e91d621f6621f241f4e396ac67c#egg=TimeSeriesD3MWrappers
RUN pip3 install -e git+https://github.com/NewKnowledge/goat-d3m-wrapper.git@08ee747242856093d93f9d692fab4fd6b7d79e2c#egg=GoatD3MWrapper

# ISI Primitives

RUN pip3 install -e git+https://github.com/usc-isi-i2/dsbox-cleaning.git@4f5a7244aee91e92d932d1f4e1ee8872b0f5c196#egg=DSBoxCleaning
RUN pip3 install datamart
