ARG VERSION=latest
ARG DOCKER_REPO
FROM $DOCKER_REPO/distil-pipeline-runner-env:$VERSION

# Using the requirements file results in a single cache layer for python packages and
# dependencies, which makes the image build very slowly when a new python package is added.
# As an optimization, we intentionally run package installation as a manual set of RUN
# commands, and ignore the requirements.txt file.  We could template this Dockerfile
# and have the build.sh script copy the contents of the requirements file in to reduce
# duplication.
#
# COPY requirements.txt ./requirements.txt
# RUN pip3 install -r requirements.txt --process-dependency-links

# D3M baseline packages - do this first because there are a lot of dependencies.
# Common primitives has a lot of dependencies that aren't used, so we stop transitive resolution.  Torch is
# the only that is required due to its use in a shared utilities function.
RUN pip3 install -e git+https://gitlab.com/datadrivendiscovery/common-primitives.git@v0.6.0#egg=common_primitives
# needed to satisfy dependencies fro dataset_map and column_map common primitives
RUN pip3 install -e git+https://gitlab.com/datadrivendiscovery/tests-data@e6299dfefcdfdc309dac0dc28b9bbf3eb9193cae#egg=test_primitives\&subdirectory=primitives
RUN pip3 install -e git+https://gitlab.com/datadrivendiscovery/ta3ta2-api.git@dist-python#egg=ta3ta2_utils

# NK Primitives
RUN pip3 install -e git+https://github.com/NewKnowledge/pcafeatures-d3m-wrapper.git@4b31ed6098236ef7392768c45e4fa2f238124d3c#egg=PcafeaturesD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/simon-d3m-wrapper.git@2c95c371f4462ffae1cf8ea1ae6902ca23539adc#egg=SimonD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/datacleaning-d3m-wrapper.git@d2666de3de1406adfad4c74f4aacaf52ceccfced#egg=DatacleaningD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/duke-d3m-wrapper.git@1c5e5f20fced72f042581a2f9cfca41557a2d85d#egg=DukeD3MWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/croc-d3m-wrapper.git@86695826d2481949c55e38020be222d231962806#egg=CROCd3mWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/unicorn-d3m-wrapper.git@865e2780e67c1f34ee2621748f557078d34eb15f#egg=UNICORNd3mWrapper
RUN pip3 install -e git+https://github.com/NewKnowledge/TimeSeries-D3M-Wrappers.git@86b8566d3767f79562ecec3316e77247b1a39061#egg=TimeSeriesD3MWrappers
RUN pip3 install -e git+https://github.com/NewKnowledge/goat-d3m-wrapper.git@e489b1fa85b8c0b4a04781d16fed7aef3ed47692#egg=GoatD3MWrapper

# ISI Primitives

RUN pip3 install -e git+https://github.com/usc-isi-i2/dsbox-cleaning.git@4f5a7244aee91e92d932d1f4e1ee8872b0f5c196#egg=DSBoxCleaning
RUN pip3 install datamart
