# based on d3m core ubuntu image which give us a python environment and the d3m core package.
FROM registry.gitlab.com/datadrivendiscovery/images/core:ubuntu-bionic-python36-v2019.1.21

RUN apt-get update

# external dependencies for NK CROC primitive
RUN apt-get install -y libleptonica-dev libtesseract-dev tesseract-ocr tesseract-ocr-eng

# RUN pip3 install wheel
RUN pip3 install 'grpcio>=1.18.0' && \
    pip3 install grpcio-tools googleapis-common-protos && \
    pip3 install mypy-protobuf && \
    pip3 install cython;

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
