# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import execute_pb2 as execute__pb2


class ExecutorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecutePipeline = channel.unary_unary(
        '/Executor/ExecutePipeline',
        request_serializer=execute__pb2.PipelineExecuteRequest.SerializeToString,
        response_deserializer=execute__pb2.PipelineExecuteResponse.FromString,
        )


class ExecutorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExecutePipeline(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ExecutorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecutePipeline': grpc.unary_unary_rpc_method_handler(
          servicer.ExecutePipeline,
          request_deserializer=execute__pb2.PipelineExecuteRequest.FromString,
          response_serializer=execute__pb2.PipelineExecuteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Executor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
