# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execute.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pipeline_pb2 as pipeline__pb2
import value_pb2 as value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='execute.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rexecute.proto\x1a\x0epipeline.proto\x1a\x0bvalue.proto\"c\n\x16PipelineExecuteRequest\x12\x31\n\x13pipelineDescription\x18\x01 \x01(\x0b\x32\x14.PipelineDescription\x12\x16\n\x06inputs\x18\x02 \x03(\x0b\x32\x06.Value\"\x19\n\x17PipelineExecuteResponse2R\n\x08\x45xecutor\x12\x46\n\x0f\x45xecutePipeline\x12\x17.PipelineExecuteRequest\x1a\x18.PipelineExecuteResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[pipeline__pb2.DESCRIPTOR,value__pb2.DESCRIPTOR,])




_PIPELINEEXECUTEREQUEST = _descriptor.Descriptor(
  name='PipelineExecuteRequest',
  full_name='PipelineExecuteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pipelineDescription', full_name='PipelineExecuteRequest.pipelineDescription', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='PipelineExecuteRequest.inputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=145,
)


_PIPELINEEXECUTERESPONSE = _descriptor.Descriptor(
  name='PipelineExecuteResponse',
  full_name='PipelineExecuteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=172,
)

_PIPELINEEXECUTEREQUEST.fields_by_name['pipelineDescription'].message_type = pipeline__pb2._PIPELINEDESCRIPTION
_PIPELINEEXECUTEREQUEST.fields_by_name['inputs'].message_type = value__pb2._VALUE
DESCRIPTOR.message_types_by_name['PipelineExecuteRequest'] = _PIPELINEEXECUTEREQUEST
DESCRIPTOR.message_types_by_name['PipelineExecuteResponse'] = _PIPELINEEXECUTERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PipelineExecuteRequest = _reflection.GeneratedProtocolMessageType('PipelineExecuteRequest', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINEEXECUTEREQUEST,
  __module__ = 'execute_pb2'
  # @@protoc_insertion_point(class_scope:PipelineExecuteRequest)
  ))
_sym_db.RegisterMessage(PipelineExecuteRequest)

PipelineExecuteResponse = _reflection.GeneratedProtocolMessageType('PipelineExecuteResponse', (_message.Message,), dict(
  DESCRIPTOR = _PIPELINEEXECUTERESPONSE,
  __module__ = 'execute_pb2'
  # @@protoc_insertion_point(class_scope:PipelineExecuteResponse)
  ))
_sym_db.RegisterMessage(PipelineExecuteResponse)



_EXECUTOR = _descriptor.ServiceDescriptor(
  name='Executor',
  full_name='Executor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=174,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecutePipeline',
    full_name='Executor.ExecutePipeline',
    index=0,
    containing_service=None,
    input_type=_PIPELINEEXECUTEREQUEST,
    output_type=_PIPELINEEXECUTERESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXECUTOR)

DESCRIPTOR.services_by_name['Executor'] = _EXECUTOR

# @@protoc_insertion_point(module_scope)
