# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from abc import (
    ABCMeta as abc___ABCMeta,
    abstractmethod as abc___abstractmethod,
)

from concurrent.futures import (
    Future as concurrent___futures___Future,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from typing import (
    Any as typing___Any,
    Callable as typing___Callable,
    Iterable as typing___Iterable,
    List as typing___List,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class EvaluationMethod(int):
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> int: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[int]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, int]]: ...
EVALUATION_METHOD_UNDEFINED = typing___cast(EvaluationMethod, 0)
HOLDOUT = typing___cast(EvaluationMethod, 1)
K_FOLD = typing___cast(EvaluationMethod, 2)
LEAVE_ONE_OUT = typing___cast(EvaluationMethod, 100)
PREDICTION = typing___cast(EvaluationMethod, 101)
TRAINING_DATA = typing___cast(EvaluationMethod, 102)

class ProgressState(int):
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> int: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[int]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, int]]: ...
PROGRESS_UNKNOWN = typing___cast(ProgressState, 0)
PENDING = typing___cast(ProgressState, 1)
RUNNING = typing___cast(ProgressState, 2)
COMPLETED = typing___cast(ProgressState, 3)
ERRORED = typing___cast(ProgressState, 4)

class ScoringConfiguration(google___protobuf___message___Message):
    method = ... # type: EvaluationMethod
    folds = ... # type: int
    train_test_ratio = ... # type: float
    shuffle = ... # type: bool
    random_seed = ... # type: int
    stratified = ... # type: bool

    def __init__(self,
        method : typing___Optional[EvaluationMethod] = None,
        folds : typing___Optional[int] = None,
        train_test_ratio : typing___Optional[float] = None,
        shuffle : typing___Optional[bool] = None,
        random_seed : typing___Optional[int] = None,
        stratified : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ScoringConfiguration: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Score(google___protobuf___message___Message):
    fold = ... # type: int
    dataset_id = ... # type: typing___Text

    @property
    def metric(self) -> ProblemPerformanceMetric: ...

    @property
    def targets(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ProblemTarget]: ...

    @property
    def value(self) -> Value: ...

    def __init__(self,
        metric : typing___Optional[ProblemPerformanceMetric] = None,
        fold : typing___Optional[int] = None,
        targets : typing___Optional[typing___Iterable[ProblemTarget]] = None,
        value : typing___Optional[Value] = None,
        dataset_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Score: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Progress(google___protobuf___message___Message):
    state = ... # type: ProgressState
    status = ... # type: typing___Text

    @property
    def start(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def end(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        state : typing___Optional[ProgressState] = None,
        status : typing___Optional[typing___Text] = None,
        start : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        end : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Progress: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class UpdateProblemRequest(google___protobuf___message___Message):
    search_id = ... # type: typing___Text

    @property
    def problem(self) -> ProblemDescription: ...

    def __init__(self,
        search_id : typing___Optional[typing___Text] = None,
        problem : typing___Optional[ProblemDescription] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> UpdateProblemRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class UpdateProblemResponse(google___protobuf___message___Message):

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> UpdateProblemResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SearchSolutionsRequest(google___protobuf___message___Message):
    user_agent = ... # type: typing___Text
    version = ... # type: typing___Text
    time_bound = ... # type: float
    priority = ... # type: float
    allowed_value_types = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[ValueType]

    @property
    def problem(self) -> ProblemDescription: ...

    @property
    def template(self) -> PipelineDescription: ...

    @property
    def inputs(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Value]: ...

    def __init__(self,
        user_agent : typing___Optional[typing___Text] = None,
        version : typing___Optional[typing___Text] = None,
        time_bound : typing___Optional[float] = None,
        priority : typing___Optional[float] = None,
        allowed_value_types : typing___Optional[typing___Iterable[ValueType]] = None,
        problem : typing___Optional[ProblemDescription] = None,
        template : typing___Optional[PipelineDescription] = None,
        inputs : typing___Optional[typing___Iterable[Value]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SearchSolutionsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SearchSolutionsResponse(google___protobuf___message___Message):
    search_id = ... # type: typing___Text

    def __init__(self,
        search_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SearchSolutionsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class EndSearchSolutionsRequest(google___protobuf___message___Message):
    search_id = ... # type: typing___Text

    def __init__(self,
        search_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> EndSearchSolutionsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class EndSearchSolutionsResponse(google___protobuf___message___Message):

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> EndSearchSolutionsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class StopSearchSolutionsRequest(google___protobuf___message___Message):
    search_id = ... # type: typing___Text

    def __init__(self,
        search_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> StopSearchSolutionsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class StopSearchSolutionsResponse(google___protobuf___message___Message):

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> StopSearchSolutionsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SolutionSearchScore(google___protobuf___message___Message):

    @property
    def scoring_configuration(self) -> ScoringConfiguration: ...

    @property
    def scores(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Score]: ...

    def __init__(self,
        scoring_configuration : typing___Optional[ScoringConfiguration] = None,
        scores : typing___Optional[typing___Iterable[Score]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SolutionSearchScore: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetSearchSolutionsResultsRequest(google___protobuf___message___Message):
    search_id = ... # type: typing___Text

    def __init__(self,
        search_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetSearchSolutionsResultsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetSearchSolutionsResultsResponse(google___protobuf___message___Message):
    done_ticks = ... # type: float
    all_ticks = ... # type: float
    solution_id = ... # type: typing___Text
    internal_score = ... # type: float

    @property
    def progress(self) -> Progress: ...

    @property
    def scores(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[SolutionSearchScore]: ...

    def __init__(self,
        progress : typing___Optional[Progress] = None,
        done_ticks : typing___Optional[float] = None,
        all_ticks : typing___Optional[float] = None,
        solution_id : typing___Optional[typing___Text] = None,
        internal_score : typing___Optional[float] = None,
        scores : typing___Optional[typing___Iterable[SolutionSearchScore]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetSearchSolutionsResultsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class DescribeSolutionRequest(google___protobuf___message___Message):
    solution_id = ... # type: typing___Text

    def __init__(self,
        solution_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> DescribeSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class PrimitiveStepDescription(google___protobuf___message___Message):
    class HyperparamsEntry(google___protobuf___message___Message):
        key = ... # type: typing___Text

        @property
        def value(self) -> Value: ...

        def __init__(self,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[Value] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> PrimitiveStepDescription.HyperparamsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...


    @property
    def hyperparams(self) -> typing___MutableMapping[typing___Text, Value]: ...

    def __init__(self,
        hyperparams : typing___Optional[typing___Mapping[typing___Text, Value]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> PrimitiveStepDescription: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SubpipelineStepDescription(google___protobuf___message___Message):

    @property
    def steps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[StepDescription]: ...

    def __init__(self,
        steps : typing___Optional[typing___Iterable[StepDescription]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SubpipelineStepDescription: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class StepDescription(google___protobuf___message___Message):

    @property
    def primitive(self) -> PrimitiveStepDescription: ...

    @property
    def pipeline(self) -> SubpipelineStepDescription: ...

    def __init__(self,
        primitive : typing___Optional[PrimitiveStepDescription] = None,
        pipeline : typing___Optional[SubpipelineStepDescription] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> StepDescription: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class DescribeSolutionResponse(google___protobuf___message___Message):

    @property
    def pipeline(self) -> PipelineDescription: ...

    @property
    def steps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[StepDescription]: ...

    def __init__(self,
        pipeline : typing___Optional[PipelineDescription] = None,
        steps : typing___Optional[typing___Iterable[StepDescription]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> DescribeSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class StepProgress(google___protobuf___message___Message):

    @property
    def progress(self) -> Progress: ...

    @property
    def steps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[StepProgress]: ...

    def __init__(self,
        progress : typing___Optional[Progress] = None,
        steps : typing___Optional[typing___Iterable[StepProgress]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> StepProgress: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SolutionRunUser(google___protobuf___message___Message):
    id = ... # type: typing___Text
    chosen = ... # type: bool
    reason = ... # type: typing___Text

    def __init__(self,
        id : typing___Optional[typing___Text] = None,
        chosen : typing___Optional[bool] = None,
        reason : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SolutionRunUser: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ScoreSolutionRequest(google___protobuf___message___Message):
    solution_id = ... # type: typing___Text

    @property
    def inputs(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Value]: ...

    @property
    def performance_metrics(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ProblemPerformanceMetric]: ...

    @property
    def users(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[SolutionRunUser]: ...

    @property
    def configuration(self) -> ScoringConfiguration: ...

    def __init__(self,
        solution_id : typing___Optional[typing___Text] = None,
        inputs : typing___Optional[typing___Iterable[Value]] = None,
        performance_metrics : typing___Optional[typing___Iterable[ProblemPerformanceMetric]] = None,
        users : typing___Optional[typing___Iterable[SolutionRunUser]] = None,
        configuration : typing___Optional[ScoringConfiguration] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ScoreSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ScoreSolutionResponse(google___protobuf___message___Message):
    request_id = ... # type: typing___Text

    def __init__(self,
        request_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ScoreSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetScoreSolutionResultsRequest(google___protobuf___message___Message):
    request_id = ... # type: typing___Text

    def __init__(self,
        request_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetScoreSolutionResultsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetScoreSolutionResultsResponse(google___protobuf___message___Message):

    @property
    def progress(self) -> Progress: ...

    @property
    def scores(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Score]: ...

    def __init__(self,
        progress : typing___Optional[Progress] = None,
        scores : typing___Optional[typing___Iterable[Score]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetScoreSolutionResultsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class FitSolutionRequest(google___protobuf___message___Message):
    solution_id = ... # type: typing___Text
    expose_outputs = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    expose_value_types = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[ValueType]

    @property
    def inputs(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Value]: ...

    @property
    def users(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[SolutionRunUser]: ...

    def __init__(self,
        solution_id : typing___Optional[typing___Text] = None,
        inputs : typing___Optional[typing___Iterable[Value]] = None,
        expose_outputs : typing___Optional[typing___Iterable[typing___Text]] = None,
        expose_value_types : typing___Optional[typing___Iterable[ValueType]] = None,
        users : typing___Optional[typing___Iterable[SolutionRunUser]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> FitSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class FitSolutionResponse(google___protobuf___message___Message):
    request_id = ... # type: typing___Text

    def __init__(self,
        request_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> FitSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetFitSolutionResultsRequest(google___protobuf___message___Message):
    request_id = ... # type: typing___Text

    def __init__(self,
        request_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetFitSolutionResultsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetFitSolutionResultsResponse(google___protobuf___message___Message):
    class ExposedOutputsEntry(google___protobuf___message___Message):
        key = ... # type: typing___Text

        @property
        def value(self) -> Value: ...

        def __init__(self,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[Value] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> GetFitSolutionResultsResponse.ExposedOutputsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

    fitted_solution_id = ... # type: typing___Text

    @property
    def progress(self) -> Progress: ...

    @property
    def steps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[StepProgress]: ...

    @property
    def exposed_outputs(self) -> typing___MutableMapping[typing___Text, Value]: ...

    def __init__(self,
        progress : typing___Optional[Progress] = None,
        steps : typing___Optional[typing___Iterable[StepProgress]] = None,
        exposed_outputs : typing___Optional[typing___Mapping[typing___Text, Value]] = None,
        fitted_solution_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetFitSolutionResultsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ProduceSolutionRequest(google___protobuf___message___Message):
    fitted_solution_id = ... # type: typing___Text
    expose_outputs = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    expose_value_types = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[ValueType]

    @property
    def inputs(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Value]: ...

    @property
    def users(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[SolutionRunUser]: ...

    def __init__(self,
        fitted_solution_id : typing___Optional[typing___Text] = None,
        inputs : typing___Optional[typing___Iterable[Value]] = None,
        expose_outputs : typing___Optional[typing___Iterable[typing___Text]] = None,
        expose_value_types : typing___Optional[typing___Iterable[ValueType]] = None,
        users : typing___Optional[typing___Iterable[SolutionRunUser]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ProduceSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ProduceSolutionResponse(google___protobuf___message___Message):
    request_id = ... # type: typing___Text

    def __init__(self,
        request_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ProduceSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetProduceSolutionResultsRequest(google___protobuf___message___Message):
    request_id = ... # type: typing___Text

    def __init__(self,
        request_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetProduceSolutionResultsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class GetProduceSolutionResultsResponse(google___protobuf___message___Message):
    class ExposedOutputsEntry(google___protobuf___message___Message):
        key = ... # type: typing___Text

        @property
        def value(self) -> Value: ...

        def __init__(self,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[Value] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> GetProduceSolutionResultsResponse.ExposedOutputsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...


    @property
    def progress(self) -> Progress: ...

    @property
    def steps(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[StepProgress]: ...

    @property
    def exposed_outputs(self) -> typing___MutableMapping[typing___Text, Value]: ...

    def __init__(self,
        progress : typing___Optional[Progress] = None,
        steps : typing___Optional[typing___Iterable[StepProgress]] = None,
        exposed_outputs : typing___Optional[typing___Mapping[typing___Text, Value]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> GetProduceSolutionResultsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SolutionExportRequest(google___protobuf___message___Message):
    fitted_solution_id = ... # type: typing___Text
    rank = ... # type: float

    def __init__(self,
        fitted_solution_id : typing___Optional[typing___Text] = None,
        rank : typing___Optional[float] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SolutionExportRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SolutionExportResponse(google___protobuf___message___Message):

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SolutionExportResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SaveSolutionRequest(google___protobuf___message___Message):
    solution_id = ... # type: typing___Text

    def __init__(self,
        solution_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SaveSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SaveSolutionResponse(google___protobuf___message___Message):
    solution_uri = ... # type: typing___Text

    def __init__(self,
        solution_uri : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SaveSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class LoadSolutionRequest(google___protobuf___message___Message):
    solution_uri = ... # type: typing___Text

    def __init__(self,
        solution_uri : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> LoadSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class LoadSolutionResponse(google___protobuf___message___Message):
    solution_id = ... # type: typing___Text

    def __init__(self,
        solution_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> LoadSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SaveFittedSolutionRequest(google___protobuf___message___Message):
    fitted_solution_id = ... # type: typing___Text

    def __init__(self,
        fitted_solution_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SaveFittedSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class SaveFittedSolutionResponse(google___protobuf___message___Message):
    fitted_solution_uri = ... # type: typing___Text

    def __init__(self,
        fitted_solution_uri : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> SaveFittedSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class LoadFittedSolutionRequest(google___protobuf___message___Message):
    fitted_solution_uri = ... # type: typing___Text

    def __init__(self,
        fitted_solution_uri : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> LoadFittedSolutionRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class LoadFittedSolutionResponse(google___protobuf___message___Message):
    fitted_solution_id = ... # type: typing___Text

    def __init__(self,
        fitted_solution_id : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> LoadFittedSolutionResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ListPrimitivesRequest(google___protobuf___message___Message):

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ListPrimitivesRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ListPrimitivesResponse(google___protobuf___message___Message):

    @property
    def primitives(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Primitive]: ...

    def __init__(self,
        primitives : typing___Optional[typing___Iterable[Primitive]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ListPrimitivesResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class HelloRequest(google___protobuf___message___Message):

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> HelloRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class HelloResponse(google___protobuf___message___Message):
    user_agent = ... # type: typing___Text
    version = ... # type: typing___Text
    allowed_value_types = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[ValueType]
    supported_extensions = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    def __init__(self,
        user_agent : typing___Optional[typing___Text] = None,
        version : typing___Optional[typing___Text] = None,
        allowed_value_types : typing___Optional[typing___Iterable[ValueType]] = None,
        supported_extensions : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> HelloResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Core(typing___Any, metaclass=abc___ABCMeta):
    @abc___abstractmethod
    def SearchSolutions(self,
        rpc_controller: typing___Any,
        request: SearchSolutionsRequest,
        done: typing___Optional[typing___Callable[[SearchSolutionsResponse], None]],
    ) -> concurrent___futures___Future[SearchSolutionsResponse]: ...
    @abc___abstractmethod
    def GetSearchSolutionsResults(self,
        rpc_controller: typing___Any,
        request: GetSearchSolutionsResultsRequest,
        done: typing___Optional[typing___Callable[[GetSearchSolutionsResultsResponse], None]],
    ) -> concurrent___futures___Future[GetSearchSolutionsResultsResponse]: ...
    @abc___abstractmethod
    def EndSearchSolutions(self,
        rpc_controller: typing___Any,
        request: EndSearchSolutionsRequest,
        done: typing___Optional[typing___Callable[[EndSearchSolutionsResponse], None]],
    ) -> concurrent___futures___Future[EndSearchSolutionsResponse]: ...
    @abc___abstractmethod
    def StopSearchSolutions(self,
        rpc_controller: typing___Any,
        request: StopSearchSolutionsRequest,
        done: typing___Optional[typing___Callable[[StopSearchSolutionsResponse], None]],
    ) -> concurrent___futures___Future[StopSearchSolutionsResponse]: ...
    @abc___abstractmethod
    def DescribeSolution(self,
        rpc_controller: typing___Any,
        request: DescribeSolutionRequest,
        done: typing___Optional[typing___Callable[[DescribeSolutionResponse], None]],
    ) -> concurrent___futures___Future[DescribeSolutionResponse]: ...
    @abc___abstractmethod
    def ScoreSolution(self,
        rpc_controller: typing___Any,
        request: ScoreSolutionRequest,
        done: typing___Optional[typing___Callable[[ScoreSolutionResponse], None]],
    ) -> concurrent___futures___Future[ScoreSolutionResponse]: ...
    @abc___abstractmethod
    def GetScoreSolutionResults(self,
        rpc_controller: typing___Any,
        request: GetScoreSolutionResultsRequest,
        done: typing___Optional[typing___Callable[[GetScoreSolutionResultsResponse], None]],
    ) -> concurrent___futures___Future[GetScoreSolutionResultsResponse]: ...
    @abc___abstractmethod
    def FitSolution(self,
        rpc_controller: typing___Any,
        request: FitSolutionRequest,
        done: typing___Optional[typing___Callable[[FitSolutionResponse], None]],
    ) -> concurrent___futures___Future[FitSolutionResponse]: ...
    @abc___abstractmethod
    def GetFitSolutionResults(self,
        rpc_controller: typing___Any,
        request: GetFitSolutionResultsRequest,
        done: typing___Optional[typing___Callable[[GetFitSolutionResultsResponse], None]],
    ) -> concurrent___futures___Future[GetFitSolutionResultsResponse]: ...
    @abc___abstractmethod
    def ProduceSolution(self,
        rpc_controller: typing___Any,
        request: ProduceSolutionRequest,
        done: typing___Optional[typing___Callable[[ProduceSolutionResponse], None]],
    ) -> concurrent___futures___Future[ProduceSolutionResponse]: ...
    @abc___abstractmethod
    def GetProduceSolutionResults(self,
        rpc_controller: typing___Any,
        request: GetProduceSolutionResultsRequest,
        done: typing___Optional[typing___Callable[[GetProduceSolutionResultsResponse], None]],
    ) -> concurrent___futures___Future[GetProduceSolutionResultsResponse]: ...
    @abc___abstractmethod
    def SolutionExport(self,
        rpc_controller: typing___Any,
        request: SolutionExportRequest,
        done: typing___Optional[typing___Callable[[SolutionExportResponse], None]],
    ) -> concurrent___futures___Future[SolutionExportResponse]: ...
    @abc___abstractmethod
    def UpdateProblem(self,
        rpc_controller: typing___Any,
        request: UpdateProblemRequest,
        done: typing___Optional[typing___Callable[[UpdateProblemResponse], None]],
    ) -> concurrent___futures___Future[UpdateProblemResponse]: ...
    @abc___abstractmethod
    def ListPrimitives(self,
        rpc_controller: typing___Any,
        request: ListPrimitivesRequest,
        done: typing___Optional[typing___Callable[[ListPrimitivesResponse], None]],
    ) -> concurrent___futures___Future[ListPrimitivesResponse]: ...
    @abc___abstractmethod
    def Hello(self,
        rpc_controller: typing___Any,
        request: HelloRequest,
        done: typing___Optional[typing___Callable[[HelloResponse], None]],
    ) -> concurrent___futures___Future[HelloResponse]: ...
    @abc___abstractmethod
    def SaveSolution(self,
        rpc_controller: typing___Any,
        request: SaveSolutionRequest,
        done: typing___Optional[typing___Callable[[SaveSolutionResponse], None]],
    ) -> concurrent___futures___Future[SaveSolutionResponse]: ...
    @abc___abstractmethod
    def LoadSolution(self,
        rpc_controller: typing___Any,
        request: LoadSolutionRequest,
        done: typing___Optional[typing___Callable[[LoadSolutionResponse], None]],
    ) -> concurrent___futures___Future[LoadSolutionResponse]: ...
    @abc___abstractmethod
    def SaveFittedSolution(self,
        rpc_controller: typing___Any,
        request: SaveFittedSolutionRequest,
        done: typing___Optional[typing___Callable[[SaveFittedSolutionResponse], None]],
    ) -> concurrent___futures___Future[SaveFittedSolutionResponse]: ...
    @abc___abstractmethod
    def LoadFittedSolution(self,
        rpc_controller: typing___Any,
        request: LoadFittedSolutionRequest,
        done: typing___Optional[typing___Callable[[LoadFittedSolutionResponse], None]],
    ) -> concurrent___futures___Future[LoadFittedSolutionResponse]: ...
class Core_Stub(Core):
    def __init__(self, rpc_channel: typing___Any) -> None: ...
    def SearchSolutions(self,
        rpc_controller: typing___Any,
        request: SearchSolutionsRequest,
        done: typing___Optional[typing___Callable[[SearchSolutionsResponse], None]],
    ) -> concurrent___futures___Future[SearchSolutionsResponse]: ...
    def GetSearchSolutionsResults(self,
        rpc_controller: typing___Any,
        request: GetSearchSolutionsResultsRequest,
        done: typing___Optional[typing___Callable[[GetSearchSolutionsResultsResponse], None]],
    ) -> concurrent___futures___Future[GetSearchSolutionsResultsResponse]: ...
    def EndSearchSolutions(self,
        rpc_controller: typing___Any,
        request: EndSearchSolutionsRequest,
        done: typing___Optional[typing___Callable[[EndSearchSolutionsResponse], None]],
    ) -> concurrent___futures___Future[EndSearchSolutionsResponse]: ...
    def StopSearchSolutions(self,
        rpc_controller: typing___Any,
        request: StopSearchSolutionsRequest,
        done: typing___Optional[typing___Callable[[StopSearchSolutionsResponse], None]],
    ) -> concurrent___futures___Future[StopSearchSolutionsResponse]: ...
    def DescribeSolution(self,
        rpc_controller: typing___Any,
        request: DescribeSolutionRequest,
        done: typing___Optional[typing___Callable[[DescribeSolutionResponse], None]],
    ) -> concurrent___futures___Future[DescribeSolutionResponse]: ...
    def ScoreSolution(self,
        rpc_controller: typing___Any,
        request: ScoreSolutionRequest,
        done: typing___Optional[typing___Callable[[ScoreSolutionResponse], None]],
    ) -> concurrent___futures___Future[ScoreSolutionResponse]: ...
    def GetScoreSolutionResults(self,
        rpc_controller: typing___Any,
        request: GetScoreSolutionResultsRequest,
        done: typing___Optional[typing___Callable[[GetScoreSolutionResultsResponse], None]],
    ) -> concurrent___futures___Future[GetScoreSolutionResultsResponse]: ...
    def FitSolution(self,
        rpc_controller: typing___Any,
        request: FitSolutionRequest,
        done: typing___Optional[typing___Callable[[FitSolutionResponse], None]],
    ) -> concurrent___futures___Future[FitSolutionResponse]: ...
    def GetFitSolutionResults(self,
        rpc_controller: typing___Any,
        request: GetFitSolutionResultsRequest,
        done: typing___Optional[typing___Callable[[GetFitSolutionResultsResponse], None]],
    ) -> concurrent___futures___Future[GetFitSolutionResultsResponse]: ...
    def ProduceSolution(self,
        rpc_controller: typing___Any,
        request: ProduceSolutionRequest,
        done: typing___Optional[typing___Callable[[ProduceSolutionResponse], None]],
    ) -> concurrent___futures___Future[ProduceSolutionResponse]: ...
    def GetProduceSolutionResults(self,
        rpc_controller: typing___Any,
        request: GetProduceSolutionResultsRequest,
        done: typing___Optional[typing___Callable[[GetProduceSolutionResultsResponse], None]],
    ) -> concurrent___futures___Future[GetProduceSolutionResultsResponse]: ...
    def SolutionExport(self,
        rpc_controller: typing___Any,
        request: SolutionExportRequest,
        done: typing___Optional[typing___Callable[[SolutionExportResponse], None]],
    ) -> concurrent___futures___Future[SolutionExportResponse]: ...
    def UpdateProblem(self,
        rpc_controller: typing___Any,
        request: UpdateProblemRequest,
        done: typing___Optional[typing___Callable[[UpdateProblemResponse], None]],
    ) -> concurrent___futures___Future[UpdateProblemResponse]: ...
    def ListPrimitives(self,
        rpc_controller: typing___Any,
        request: ListPrimitivesRequest,
        done: typing___Optional[typing___Callable[[ListPrimitivesResponse], None]],
    ) -> concurrent___futures___Future[ListPrimitivesResponse]: ...
    def Hello(self,
        rpc_controller: typing___Any,
        request: HelloRequest,
        done: typing___Optional[typing___Callable[[HelloResponse], None]],
    ) -> concurrent___futures___Future[HelloResponse]: ...
    def SaveSolution(self,
        rpc_controller: typing___Any,
        request: SaveSolutionRequest,
        done: typing___Optional[typing___Callable[[SaveSolutionResponse], None]],
    ) -> concurrent___futures___Future[SaveSolutionResponse]: ...
    def LoadSolution(self,
        rpc_controller: typing___Any,
        request: LoadSolutionRequest,
        done: typing___Optional[typing___Callable[[LoadSolutionResponse], None]],
    ) -> concurrent___futures___Future[LoadSolutionResponse]: ...
    def SaveFittedSolution(self,
        rpc_controller: typing___Any,
        request: SaveFittedSolutionRequest,
        done: typing___Optional[typing___Callable[[SaveFittedSolutionResponse], None]],
    ) -> concurrent___futures___Future[SaveFittedSolutionResponse]: ...
    def LoadFittedSolution(self,
        rpc_controller: typing___Any,
        request: LoadFittedSolutionRequest,
        done: typing___Optional[typing___Callable[[LoadFittedSolutionResponse], None]],
    ) -> concurrent___futures___Future[LoadFittedSolutionResponse]: ...