# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Primitive(google___protobuf___message___Message):
    id = ... # type: typing___Text
    version = ... # type: typing___Text
    python_path = ... # type: typing___Text
    name = ... # type: typing___Text
    digest = ... # type: typing___Text

    def __init__(self,
        id : typing___Optional[typing___Text] = None,
        version : typing___Optional[typing___Text] = None,
        python_path : typing___Optional[typing___Text] = None,
        name : typing___Optional[typing___Text] = None,
        digest : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Primitive: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"digest",u"id",u"name",u"python_path",u"version"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[b"digest",b"id",b"name",b"python_path",b"version"]) -> None: ...
