# @generated by generate_proto_mypy_stubs.py.  Do not edit!
from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)


class ValueType(int):
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> int: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[int]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, int]]: ...
VALUE_TYPE_UNDEFINED = typing___cast(ValueType, 0)
RAW = typing___cast(ValueType, 1)
DATASET_URI = typing___cast(ValueType, 2)
CSV_URI = typing___cast(ValueType, 3)
PICKLE_URI = typing___cast(ValueType, 4)
PICKLE_BLOB = typing___cast(ValueType, 5)
PLASMA_ID = typing___cast(ValueType, 6)

class NullValue(int):
    @classmethod
    def Name(cls, number: int) -> str: ...
    @classmethod
    def Value(cls, name: str) -> int: ...
    @classmethod
    def keys(cls) -> typing___List[str]: ...
    @classmethod
    def values(cls) -> typing___List[int]: ...
    @classmethod
    def items(cls) -> typing___List[typing___Tuple[str, int]]: ...
NULL_VALUE = typing___cast(NullValue, 0)

class ValueError(google___protobuf___message___Message):
    message = ... # type: typing___Text

    def __init__(self,
        message : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ValueError: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ValueList(google___protobuf___message___Message):

    @property
    def items(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[ValueRaw]: ...

    def __init__(self,
        items : typing___Optional[typing___Iterable[ValueRaw]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ValueList: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ValueDict(google___protobuf___message___Message):
    class ItemsEntry(google___protobuf___message___Message):
        key = ... # type: typing___Text

        @property
        def value(self) -> ValueRaw: ...

        def __init__(self,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[ValueRaw] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> ValueDict.ItemsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...


    @property
    def items(self) -> typing___MutableMapping[typing___Text, ValueRaw]: ...

    def __init__(self,
        items : typing___Optional[typing___Mapping[typing___Text, ValueRaw]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ValueDict: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class ValueRaw(google___protobuf___message___Message):
    null = ... # type: NullValue
    double = ... # type: float
    int64 = ... # type: int
    bool = ... # type: bool
    string = ... # type: typing___Text
    bytes = ... # type: bytes

    @property
    def list(self) -> ValueList: ...

    @property
    def dict(self) -> ValueDict: ...

    def __init__(self,
        null : typing___Optional[NullValue] = None,
        double : typing___Optional[float] = None,
        int64 : typing___Optional[int] = None,
        bool : typing___Optional[bool] = None,
        string : typing___Optional[typing___Text] = None,
        bytes : typing___Optional[bytes] = None,
        list : typing___Optional[ValueList] = None,
        dict : typing___Optional[ValueDict] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ValueRaw: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...

class Value(google___protobuf___message___Message):
    dataset_uri = ... # type: typing___Text
    csv_uri = ... # type: typing___Text
    pickle_uri = ... # type: typing___Text
    pickle_blob = ... # type: bytes
    plasma_id = ... # type: bytes

    @property
    def error(self) -> ValueError: ...

    @property
    def raw(self) -> ValueRaw: ...

    def __init__(self,
        error : typing___Optional[ValueError] = None,
        raw : typing___Optional[ValueRaw] = None,
        dataset_uri : typing___Optional[typing___Text] = None,
        csv_uri : typing___Optional[typing___Text] = None,
        pickle_uri : typing___Optional[typing___Text] = None,
        pickle_blob : typing___Optional[bytes] = None,
        plasma_id : typing___Optional[bytes] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Value: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
